"""
Asignación de metadatos por defecto para archivos soportados.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Optional

import piexif
from PIL import Image, PngImagePlugin
from PyPDF2 import PdfReader, PdfWriter
from docx import Document

from .utils_modifier import ensure_editable_file, ensure_output_path

DEFAULT_AUTHOR = "MetadataAnalyzer"
DEFAULT_TITLE = "Processed Document"


def _get_current_timestamp() -> str:
    """Devuelve la marca de tiempo UTC en un formato estándar."""
    return datetime.utcnow().strftime("%Y:%m:%d 00:00:00")


def apply_default_pdf_metadata(file_path: str | Path, destination: Optional[str | Path] = None) -> Path:
    """
    Añade metadatos por defecto estándar a un archivo PDF.
    """
    source_file = ensure_editable_file(file_path)
    output_file = ensure_output_path(source_file, destination, suffix="_default")
    
    reader = PdfReader(str(source_file))
    writer = PdfWriter()
    
    for page in reader.pages:
        writer.add_page(page)
        
    writer.add_metadata({
        "/Author": DEFAULT_AUTHOR,
        "/Title": DEFAULT_TITLE,
        "/Producer": "MetadataAnalyzer Tool",
        "/Creator": "Automated CLI",
        "/CreationDate": _get_current_timestamp(),
    })
    
    with output_file.open("wb") as f:
        writer.write(f)
        
    return output_file


def apply_default_docx_metadata(file_path: str | Path, destination: Optional[str | Path] = None) -> Path:
    """
    Establece propiedades principales por defecto para un archivo DOCX.
    """
    source_file = ensure_editable_file(file_path)
    output_file = ensure_output_path(source_file, destination, suffix="_default")
    
    doc = Document(str(source_file))
    props = doc.core_properties
    
    props.author = DEFAULT_AUTHOR
    props.title = DEFAULT_TITLE
    props.subject = "Generated by MetadataAnalyzer"
    props.comments = "Metadata reset to defaults."
    props.last_modified_by = DEFAULT_AUTHOR
    props.category = "Security"
    
    doc.save(str(output_file))
    return output_file


def apply_default_image_metadata(file_path: str | Path, destination: Optional[str | Path] = None) -> Path:
    """
    Sobrescribe los metadatos de la imagen con un conjunto mínimo por defecto.
    """
    source_file = ensure_editable_file(file_path)
    output_file = ensure_output_path(source_file, destination, suffix="_default")
    
    with Image.open(str(source_file)) as img:
        format_name = (img.format or "").upper()
        
        if format_name in {"JPEG", "JPG", "TIFF", "HEIC", "HEIF"}:
            # Crea un bloque EXIF limpio
            exif_dict = {
                "0th": {
                    piexif.ImageIFD.Make: DEFAULT_AUTHOR,
                    piexif.ImageIFD.Software: "MetadataAnalyzer CLI",
                    piexif.ImageIFD.Artist: DEFAULT_AUTHOR,
                },
                "Exif": {
                    piexif.ExifIFD.DateTimeOriginal: _get_current_timestamp(),
                },
            }
            exif_bytes = piexif.dump(exif_dict)
            img.save(str(output_file), format=img.format, exif=exif_bytes)
            
        else:
            # Para PNGs, usa fragmentos de texto
            png_info = PngImagePlugin.PngInfo()
            png_info.add_text("Author", DEFAULT_AUTHOR)
            png_info.add_text("Software", "MetadataAnalyzer CLI")
            png_info.add_text("Description", DEFAULT_TITLE)
            img.save(str(output_file), format=img.format, pnginfo=png_info)
            
    return output_file
